name: "CI - Test Features"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - flutter
          - buf
          - opencommit
          - ros2
        baseImage:
          - debian
          - ubuntu
        exclude:
          # ROS2 typically works better with Ubuntu
          - features: ros2
            baseImage: debian
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: timeout 900 devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i mcr.microsoft.com/devcontainers/base:${{ matrix.baseImage }}

  test-scenarios:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - flutter
          - buf
          - opencommit
          - ros2
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing '${{ matrix.features }}' scenarios"
        run: timeout 900 devcontainer features test -f ${{ matrix.features }}
